### ISSUE TITLE
CO TO ZA GOWNO

### ISSUE THREAD

**Issue by tapczanek1321** [Gwardia-Czapli/Grzybobranie#1]
nie podoba mi sie >:(

**Comment by Norbiros** [comment]
Witamy Panie tapczanie! Właśnie odkrył Pan funkcjonalność GitHuba o nazwie issusue. Muszę poinformować Pana że to jest tymczasowe repozytorium kodu, abyśmy na spotkaniach gwardi mogli pięknie Wam prezentować. Proszę nie przejmować, niedługo usuniemy ten problem na wieki <3 *uwu*

**Comment by tapczanek1321** [comment]
isusułe
