### ISSUE TITLE
Ludzie narzekają a ja nwm co zrobić

### ISSUE THREAD

**Issue by mokoszerosy** [Gwardia-Czapli/Grzybobranie#13]
Wtf ja coś zrobiłem, coś zmieniłem coś pushnołem ale nie widzę tego tutej i nwm help.

**Comment by mokoszerosy** [comment]
Bo u mnie się pokazuje że nie ma zmian a u mnie jest inaczej niż tutaj.
Nie wiem o co chodzi weź że ktoś pomóż bo to pieprzone wariactwo nie działa jak trzeba.

**Comment by goteusz-maszyk** [comment]
pomogę jak @Norbiros mnie wróci
