### ISSUE TITLE
Skill issue

### ISSUE THREAD

**Issue by Gozittopl** [Gwardia-Czapli/Grzybobranie#3]
Poćwicz

**Comment by Norbiros** [comment]
🙈🙉🙊

**Comment by Sanielia** [comment]
Witam, zły dział! Ten temat był już poruszany na forum! Jako, że jesteś nowy to tym razem skończy się tylko na warnie ale w przyszłości UŻYJ OPCJI SZUKAJ. Pozdrawiam, moderator forum wypieki.net
